// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyWithStructure
{
    internal sealed partial class Vsix
    {
        public const string Id = "CopyWithStructure.5b3642f3-3335-490d-98fd-149c9248f86f";
        public const string Name = "CopyWithStructure";
        public const string Description = @"Copy files with folder structure.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Oswaldo Waskarali";
        public const string Tags = "";
    }
}
